//
//  Zap
//
//  Created by Otto Suess on 20.05.18.
//  Copyright © 2018 Zap. All rights reserved.
//

import Foundation

/// the qrCode or json generated by zapconnect
/// zapconnect is deprecated and superseded by lndconnect
struct ZapconnectQRCode: Decodable {
    let certificate: String?
    let macaroon: Data
    let url: URL

    enum CodingKeys: String, CodingKey {
        case certificate = "c"
        case macaroon = "m"
        case url = "ip"
    }

    var rpcCredentials: RPCCredentials {
        return RPCCredentials(certificate: certificate, macaroon: macaroon, host: url)
    }

    init?(json: String) {
        guard
            let data = json.data(using: .utf8),
            let remoteNodeConfiguration = try? JSONDecoder().decode(ZapconnectQRCode.self, from: data)
            else { return nil }
        self = remoteNodeConfiguration
    }
}
